---
title: "p8105_hw6_unp2000"
author: Uma Palaniappan 
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
child_data = read_csv("./data/birthweight.csv") %>%
janitor::clean_names () %>%
  mutate( 
      babysex = factor(babysex, levels = c(1,2), labels = c("male", "female")), 
      frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9), labels = c("white", "black", "asian", "puerto rican", "other", "unknown")),
      mrace = factor(mrace, levels = c(1, 2, 3, 4, 8, 9), labels = c("white", "black", "asian", "puerto rican", "other", "unknown")),
      malform = factor(malform, levels = c(0,1), labels = c("absent", "present"))
      )
```

# Regression Model 

Creating Initial Regression Model: 

Variables were selected based on a literature search of predictors of low birthweight. Based on this, babysex, gaweeks, momage, mheight, parity, ppbmi, pnumlbw, and smoken were selected as variables to include in the model. 

```{r}
bw_model1 = lm(bwt ~ babysex + gaweeks + momage + mheight + parity + ppbmi + pnumlbw + smoken, data = child_data)
```

Plotting residuals against fitted values: 

```{r}
plot_1 = child_data %>%
  modelr::add_residuals(bw_model1) %>%
  modelr::add_predictions(bw_model1) %>%
  ggplot(aes(x = pred, y = resid)) + geom_point (color = "blue") 

plot_1
```

